package com.leanr_spring_boot.MySecondWebApp.controller;

import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.ResponseBody;

@Controller
public class SayHelloController {
	
	@RequestMapping("say-hello")
	@ResponseBody
	public String sayHello() {
		return "Hello there how are you ?";
	}
	
	@RequestMapping("/sample-html")
	  @ResponseBody
	  public String getSampleHtml() {
	    StringBuilder builder = new StringBuilder();
	    builder.append("<!DOCTYPE html><html><head><title>Sample Page</title></head>");
	    builder.append("<body><h1>This is a sample HTML page</h1>");
	    builder.append("<p>Generated by Spring Controller</p>");
	    builder.append("</body></html>");
	    return builder.toString();
	  }
	
	 @RequestMapping("/sample-jsp")
	  public String sayhelloojsp() {
	    
	    return "hello";
	  }
}
